[2021-05-12 16:32:11] Request: 
open_dataset(ds_id=esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.MSAAI.1-7.r1, store_id=cci-store, time_range=None, var_names=['number_of_positive_observations', 'positive_absorbing_aerosol_index'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 354, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
[2021-05-12 16:55:34] Request: 
open_dataset(ds_id=esacci.AEROSOL.mon.L3.AAI.multi-sensor.multi-platform.MSAAI.1-7.r1, store_id=cci-store, time_range=None, var_names=['number_of_observations', 'positive_absorbing_aerosol_index'], region=None)

Traceback (most recent call last):
  File "test_cci_data_support.py", line 354, in test_open_ds
    time_range = get_time_range(data_descriptor, dataset)
  File "test_cci_data_support.py", line 77, in get_time_range
    time_delta = pd.Timedelta(int(data_descriptor.time_period[:-1]),
  File "pandas/_libs/tslibs/timedeltas.pyx", line 1177, in pandas._libs.tslibs.timedeltas.Timedelta.__new__
ValueError: Units 'M', 'Y', and 'y' are no longer supported, as they do not represent unambiguous timedelta values durations.
